version: 2
jobs:
  build:
    working_directory: ~/actionstore/dummy

    steps:
      - checkout:
          path: ~/actionstore

      # Restore Cached Dependencies
      - type: cache-restore
        name: Restore bundle cache
        key: cv-{{ checksum "Gemfile.lock" }}

      # Bundle install dependencies
      - run: bundle install --path vendor/bundle
      
      # Cache Dependencies
      - type: cache-save
        name: Store bundle cache
        key: cv-{{ checksum "Gemfile.lock" }}
        paths:
          - vendor/bundle

      - type: cache-restore
        name: Restore npm cache
        key: cv-{{ checksum "package-lock.json" }}

      - run: npm install --immutable

      # Install peer dependency (this is automatic in NPM 7, but circleci doesnt do it)
      - run: npm install --save @rails/actioncable

        # Cache Dependencies
      - type: cache-save
        name: Store npm cache
        key: cv-{{ checksum "package-lock.json" }}
        paths:
          - ~/.cache/npm

      # Setup the environment
      #- run: cp .sample.env .env

      # Setup the database
      - run: bundle exec rake db:setup

      - run: bin/vite build --clear --mode=test

      # Run the tests
      - run: bundle exec rake test:system test

      - store_test_results:
          path: test/reports